version: "3.9"
services:
    game_rytorcraps:
        # Path to dockerfile.
        # '.' represents the current directory in which
        # docker-compose.yml is present.
        build: "./Rytor.Craps.Microservices.Game/Rytor.Craps.Microservices.Game"
    
        # Mapping of container port to host
        
        ports:
          - "5006:5006"
    
    account_rytorcraps:
        # Path to dockerfile.
        # '.' represents the current directory in which
        # docker-compose.yml is present.
        build: "./Rytor.Craps.Microservices.Account/Rytor.Craps.Microservices.Account"
    
        # Mapping of container port to host
        
        ports:
          - "5002:5002"

    balance_rytorcraps:
         # Path to dockerfile.
        # '.' represents the current directory in which
        # docker-compose.yml is present.
        build: "./Rytor.Craps.Microservices.Balance/Rytor.Craps.Microservices.Balance"
    
        # Mapping of container port to host
        
        ports:
          - "5004:5004"

    orchestrator_rytorcraps:
        # Path to dockerfile.
        # '.' represents the current directory in which
        # docker-compose.yml is present.
        build: "./Rytor.Craps.Microservices.Orchestrator/Rytor.Craps.Microservices.Orchestrator"
    
        # Mapping of container port to host
        
        ports:
          - "5000:5000"