version: "3.9"
services:
  database_rytorcraps:
    build: "./db"
    args:
      SA_PASSWORD: $SA_PASSWORD
    ports:
      - "1433:1433"
    volumes:
      - /var/opt/mssql/data
      - /var/opt/mssql/log
      - /var/opt/mssql/secrets

  game_rytorcraps:
    build: "./Rytor.Craps.Microservices.Game/Rytor.Craps.Microservices.Game"
    args:
      SA_PASSWORD: $SA_PASSWORD    
    ports:
      - "5006:5000"
    
  account_rytorcraps:
    build: "./Rytor.Craps.Microservices.Account/Rytor.Craps.Microservices.Account"
    args:
      SA_PASSWORD: $SA_PASSWORD
    ports:
      - "5002:5000"

  balance_rytorcraps:
    build: "./Rytor.Craps.Microservices.Balance/Rytor.Craps.Microservices.Balance"
    args:
      SA_PASSWORD: $SA_PASSWORD
    ports:
      - "5004:5000"

  ui_rytorcraps:
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: "./rytor-craps-ui"
    
    # Mapping of container port to host  
    ports:
      - "80:3000"
