namespace Rytor.Craps.Microservices.Game.Models
{
    public enum GameEvent
    {
        Pass,
        DontPass,
        Field,
        BigSix,
        BigEight,
        Come,
        DontCome,
        Four,
        Five,
        Six,
        Eight,
        Nine,
        Ten,
        C,
        E,
        Seven,
        Craps,
        HardSix,
        HardTen,
        HardEight,
        HardFour,
        Three,
        Two,
        Twelve,
        Eleven
    }
}