insert into BetStatus (Description) VALUES ('Open');
insert into BetStatus (Description) VALUES ('Cancelled');
insert into BetStatus (Description) VALUES ('Push');
insert into BetStatus (Description) VALUES ('Won');
insert into BetStatus (Description) VALUES ('Lost');
insert into GameEvent (Description) VALUES ('Pass');
insert into GameEvent (Description) VALUES ('DontPass');
insert into GameEvent (Description) VALUES ('Field');
insert into GameEvent (Description) VALUES ('BigSix');
insert into GameEvent (Description) VALUES ('BigEight');
insert into GameEvent (Description) VALUES ('Come');
insert into GameEvent (Description) VALUES ('DontCome');
insert into GameEvent (Description) VALUES ('Four');
insert into GameEvent (Description) VALUES ('Five');
insert into GameEvent (Description) VALUES ('Six');
insert into GameEvent (Description) VALUES ('Eight');
insert into GameEvent (Description) VALUES ('Nine');
insert into GameEvent (Description) VALUES ('Ten');
insert into GameEvent (Description) VALUES ('C');
insert into GameEvent (Description) VALUES ('E');
insert into GameEvent (Description) VALUES ('Seven');
insert into GameEvent (Description) VALUES ('Craps');
insert into GameEvent (Description) VALUES ('HardFour');
insert into GameEvent (Description) VALUES ('HardSix');
insert into GameEvent (Description) VALUES ('HardEight');
insert into GameEvent (Description) VALUES ('HardTen');
insert into GameEvent (Description) VALUES ('Three');
insert into GameEvent (Description) VALUES ('Two');
insert into GameEvent (Description) VALUES ('Twelve');
insert into GameEvent (Description) VALUES ('Eleven');
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (1, 1, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (2, 1, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (3, 1, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (4, 1, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (5, 1, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (6, 1, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (7, 1, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (8, 9, 5);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (9, 7, 5);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (10, 7, 6);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (11, 7, 6);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (12, 7, 5);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (13, 9, 5);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (14, 3, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (15, 7, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (16, 1, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (17, 1, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (18, 7, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (19, 9, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (20, 9, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (21, 7, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (22, 15, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (23, 30, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (24, 30, 1);
insert into GameEventPayout (GameEventId, PayoutOddsLeft, PayoutOddsRight) VALUES (25, 15, 1);
